### ISSUE TITLE
biggan

### ISSUE THREAD

**Issue by thomwolf** [yk/clip_music_video#1]
Thanks for the nice video Yannic.

Would have appreciate a mention or keeping the licence on the BigGan code.

I usually don't care too much about people copying my code around and removing licences but for some reason reverse-engineering this model directly from the block-box TF graph of TF-Hub took me a few painful nights (in particular the weirdly stored BatchNorm statistics) so it's close to my heart.

**Comment by yk** [comment]
Thanks a lot for notifying me, this is really important. I thought I tracked all references.
I hope it's fixed now. I'll do another pass over the rest.
